<?php

return [
    '10_questions' => 'Here are 10 most Frequent Asked Questions about Thoth.',
    'common_questions' => 'Common Questions:',

    'question1' => 'What is Thoth?',
    'answer1' => 'Thoth is a powerful tool to support collaborative systematic reviews. It is a multi-platform solution developed to automate important parts of the systematic review process, facilitating and streamlining the work of researchers and professionals involved in this type of study.',

    'question2' => 'What are the main features of Thoth?',
    'answer2' => 'Thoth\'s main functionalities include: automated generation of search strings, management of studies in the selection and quality stages, generation of data for use in scientific works, generation of graphs and tables, creation of detailed reports and collaboration between team members.',

    'question3' => 'What technologies were used in the development of Thoth?',
    'answer3' => 'Thoth was developed using the following technologies: PHP Language, MySQL, Git, Laravel Framework, Docker, Bootstrap, Migrations, PHPSpreadSheet, League/CSV, PHPUnit, JavaScript and Git Actions.',

    'question4' => 'Who are responsible for the development and maintenance of Thoth?',
    'answer4' => 'Thoth was created by undergraduate Software Engineering students and is maintained and updated by students and professors from the Graduate Program in Software Engineering (PPGES) at the Federal University of Pampa (UNIPAMPA).',

    'question5' => 'Is Thoth an open source tool? What license is used?',
    'answer5' => 'Yes, Thoth is an open source project. It is licensed under the MIT License, which allows its use, modification and distribution freely, as long as the copyright and original license are maintained.',

    'question6' => 'Is Thoth a cross-platform tool? What devices does it support?',
    'answer6' => 'Yes, Thoth is designed to work on different platforms such as computers, tablets and smartphones. This allows users to work collaboratively in a shared virtual environment, regardless of the device used.',

    'question7' => 'How does Thoth automate parts of the systematic review process?',
    'answer7' => 'Thoth automates many steps of the systematic review process, reducing the need for manual work and minimizing errors. It generates search strings, manages studies in the selection and quality steps, generates structured data, creates charts and tables, and produces detailed reports on the process steps.',

    'question8' => 'What are the study management functionalities offered by Thoth?',
    'answer8' => 'Thoth offers functionality for importing studies, selecting studies based on criteria, checking duplicate studies, viewing study information, assessing study quality and resolving conflicts generated by classification differences.',

    'question9' => 'How does Thoth generate structured and organized data for use in scientific work?',
    'answer9' => 'Thoth is capable of extracting relevant data from selected studies, allowing researchers to answer extraction questions. These data are then organized and structured, ready to be used in scientific work, facilitating the analysis and interpretation of the results obtained.',

    'question10' => 'Does Thoth offer the generation of graphs, tables and reports? How can these results be shared?',
    'answer10' => 'Yes, Thoth offers automatic generation of graphs, tables and reports. These visual representations help to clearly and objectively visualize the progress and results of the systematic review steps. Results can be shared by exporting reports in different formats, such as PDF or Word, facilitating the communication of results with colleagues and supervisors.',
];
